config/routes.rb
MusicObserver::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "api_session/outside_request"
  get "api_session/return_callback"

  resources :recommendations, only: [:index, :destroy] do
    collection do
      post 'api_parse'
    end
  end

  resources :concerts, only: [:index] do
    member do
      put 'hide'
    end
  end

  resources :favorites, except: [:show] do
    collection do
      get 'api_search'
      post 'api_library'
      put 'pack_track'
    end

    member do
      put 'track'
    end
  end

  devise_for :users

  get "main/index"
  get "main/api_autenticate"
  
  get "schedule_logs" => 'schedule_logs#index'
  delete "schedule_logs" => 'schedule_logs#destroy'
  

  root :to => 'main#index'

end

app/models/favorite.rb
class Favorite < ArtistUser
  attr_accessible :artist_id, :user_id, :track, :show, :listeners
  belongs_to :user
  belongs_to :artist
  after_create :check_duplicates
  before_update :toggle_user_concerts

  private 
  def toggle_user_concerts
  	if track
	    artist.concerts.actual.each do |concert|
				if user.concerts.include?(concert)
					user.concert_user_entries.where(concert_id: concert).update_all(is_show: true)
				else
					user.concert_user_entries.create(concert: concert) 
				end
			end
		else
			artist.concerts.each do |concert|
				user.concert_user_entries.where(concert_id: concert).update_all(is_show: false)
			end
		end	
  end

  def check_duplicates
    Recommendation.where(artist_id: artist_id, user_id: user).delete_all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @search = Favorite.order('created_at desc').includes(:artist).where(user_id: current_user.id).search(params[:q])
    @favorites = @search.result.paginate(page: params[:page], per_page: params[:per_page] || 10) 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favorites }
    end
  end

  def api_search
    artists = @api_provider.search_artist( params[:query] )
    known_artists = current_user.artists_favorites.find_all_by_mbid(artists.collect {|n| n[:mbid] }).map(&:mbid)
    artists.select! {|artist| !known_artists.include?(artist[:mbid]) }
    render json: artists      
  end

  def api_library
    user = ''
    if !params[:api_id].blank?
      return failed_action(t('errors.messages.empty_api_id')) unless @api_provider.check_user(params[:api_id])
      user = params[:api_id]
    else 
      if (user = @api_provider_aut.username).nil?
        return api_auth()
      end
    end
   UserLibraryParser.new.delay.perform(user, current_user.id)
    respond_to do |format|
      format.html { flash[:success] = t(:started_parsing); redirect_to :back }
      format.json { render json: { title: t(:success), message: t(:started_parsing) } }
    end
  end

  def new
    @favorite = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  # POST /artists
  # POST /artists.json
  def create
    @favorite = Artist.find_or_create(params)
    current_user.favorites.create(artist_id: @favorite.id, track: params[:track] || false)
    toggle_user_concerts()

    respond_to do |format|
      format.html { redirect_to :index, notice: t(:entry_created) }
      format.json { render json: @favorite, status: :created }
    end
  end

  def destroy
    @favorite = current_user.favorites.find_by_artist_id(params[:id])
    respond_to do |format|
      if @favorite.destroy()
        format.html { redirect_to :back, notice: t(:entry_destroied) }
        format.json { render json: @favorite, status: :created }  
      else
        format.html { redirect_to :back, error: server_error_message }
        format.json { render_json_error(server_error_message) }
      end
    end
  end

  def track
    @favorite = current_user.favorites.find_by_artist_id(params[:id])

    respond_to do |format|
      if @favorite.update_attribute(:track, params[:track])
        format.html { redirect_to :back, notice: t(:entry_updated) }
        format.json { render json: { title: t('update'), message: t('update_success') } }
      else
        format.html { redirect_to :back, error: server_error_message }
        format.json { render_json_error(server_error_message) }
      end
    end
  end

  def pack_track  
    @favorites = current_user.favorites
    @favorites = @favorites.where(:artist_id => params[:artists]) unless params[:artists].blank?
    
    respond_to do |format|
      if @favorites.update_all(track: (params[:track] || true))
        format.html { redirect_to :back, notice: t(:entry_updated) }
        format.json { render json: { title: t('update'), message: t('update_success') } }
      else
        format.html { redirect_to :back, error: server_error_message }
        format.json { render_json_error(server_error_message) }
      end
    end
  end

  private
  def failed_action(message)
    respond_to do |format|
      format.html { redirect_to :back, error: message }
      format.json { render_json_error(message) }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.haml
- tracked = favorite.track
- cache("favorite_#{favorite.artist.id}_#{tracked ? 'tracked' : 'untracked'}") do
  %tr
    %td 
      - artist = favorite.artist
      %span{class: "label label-success #{('hidden' unless tracked)}",  }
        = t('.tracked')
      %span{class: "label label-default #{('hidden' if tracked)}" }
        = t('.not_tracked')
    %td= link_to artist.name, artist.api_link, class: 'external '
    %td
      = link_to track_favorite_path(artist.id, :track => true), :method => :put do 
        %button{ type: 'button', class: "btn #{('hidden' if tracked)}", }
          = t('.track')
      = link_to track_favorite_path(artist.id, :track => false), :method => :put do 
        %button{ type: 'button', class: "btn #{('hidden' unless tracked)}" }
          = t('.untrack')
    %td= artist.mbid
    %td= image_tag artist.photo.url
    %td=l artist.created_at
    %td
      = link_to t('.destroy', :default => t("helpers.links.destroy")), favorite_path(artist), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
    %td
      = check_box_tag artist.id

app/views/favorites/_form.html.haml
= form_tag favorites_path, :remote => true, :class => 'form-horizontal', id: 'favorites_form'  do 
  .control-group
    = label_tag :name, nil, :class => 'control-label'
    .controls
      = text_field_tag :name, nil, :class => 'text_field'
      %button#search_favorite{'data-loading-text' => 'Загрузка...'}
        Найти
  = hidden_field_tag :mbid
  = hidden_field_tag :image
  .control-group
    = label_tag :track, false, :class => 'control-label'
    .controls
      = check_box_tag :track, true, false
  #submit_favorites.form-actions
    = submit_tag 'Отправить', :class => 'btn btn-primary', 'data-loading-text' => 'Отправляю...'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), favorites_path, :class => 'btn'
  #response
  #favorites_search_results

app/views/favorites/_parse_remote_account.html.haml
= link_to t(:add_from_library), '#', :class => 'btn btn-primary', id: 'add_library_button'

- form_params = { method: :post, id: 'api_library' }
- form_params.merge!({ remote: true, class: 'simple_remote', 'data-type' => 'json', 'data-loading-text' => t(:in_work) }) if @api_authorized
= form_tag api_library_favorites_path, form_params  do
  %h5= t('.remote_user_login')
  = text_field_tag 'api_id', nil
  = submit_tag t(:add), :confirm => t('.parsing_message')
  = link_to_or_authorize(@api_authorized, submit_tag(t('.add_from_own_library'), :confirm => t('.parsing_message'), id: 'add_from_own_library'))

app/views/favorites/_search.html.haml
%p.lead
  %h5
    = t(".search")
  = search_form_for @search, :class => "navbar-form navbar-left", role: "search" do |f|
    = f.text_field :artist_name_cont, placeholder: Favorite.human_attribute_name(:name)
    = f.text_field :artist_created_at_gt, placeholder: t(:date_from), id: :date_from
    = f.text_field :artist_created_at_lt, placeholder: t(:date_to), id: :date_to
    = t('.only_tracked')
    = f.check_box :track_eq
    = t(:per_page)
    = select_tag :per_page, options_for_select((25..200).step(25), selected: params[:per_page])
    = f.submit t(:search)
    = f.submit t(:clear), :id => :q_reset

app/views/favorites/api_library.html.haml
%h2
  api_library

app/views/favorites/index.html.haml
- model_class = Favorite
.page-header
  %h1=model_page_title(model_class)
= link_to t('.create', :default => t("helpers.links.new")), new_favorite_path, :class => 'btn btn-primary'
= render 'parse_remote_account'  
= render partial: 'search'
  
- if @favorites.any?
  = link_to pack_track_favorites_path(), :method => :put, confirm: t('.track_confirm') do 
    %button.btn{ type: 'button' }
      = t('.track_all_library')
  %table.table.table-striped#favorite_table
    %thead
      %tr
        %th= model_class.human_attribute_name(:status)
        %th= sort_link @search, :artist_name
        %th= sort_link @search, :track
        %th= model_class.human_attribute_name(:mbid)
        %th= model_class.human_attribute_name(:photo)
        %th= sort_link @search, :artist_created_at
        %th= t'.actions', :default => t("helpers.actions")
        %th
          %button.btn.select_all{ type: 'button' }
            %i.icon-arrow-down{ title: t(:check_all) }
          %br
          = form_tag pack_track_favorites_path(), id: 'pack_track_form', :method => :put, 'data-type' => 'json', class: 'simple_remote' do
            = hidden_field_tag :track, true
          %button.btn{ type: 'button', id: 'pack_track', title: t('.track_all_page_title') }
            = t('.track_all_button')
          %button.btn{ type: 'button', id: 'pack_track_none', title: t('.none_track_all_page_title') }
            = t('.track_none_button')
    %tbody
      = render partial: "favorite", collection: @favorites
  = will_paginate @favorites
- else
  = render 'main/empty_resource'         

app/views/favorites/new.html.haml
- model_class = Favorite
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/favorites/show.html.haml
- model_class = Favorite
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @favorite.name
%p
  %strong= model_class.human_attribute_name(:track) + ':'
  %br
  = @favorite.track
%p
  %strong= model_class.human_attribute_name(:mbid) + ':'
  %br
  = @favorite.mbid
%p
  %strong= model_class.human_attribute_name(:photo_file_name) + ':'
  %br
  = @favorite.photo.url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), favorites_path, :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), favorite_path(@favorite), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'