config/routes.rb
MusicObserver::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "api_session/outside_request"
  get "api_session/return_callback"

  resources :recommendations, only: [:index, :destroy] do
    collection do
      post 'api_parse'
    end
  end

  resources :concerts, only: [:index] do
    member do
      put 'hide'
    end
  end

  resources :favorites, except: [:show] do
    collection do
      get 'api_search'
      post 'api_library'
      put 'pack_track'
    end

    member do
      put 'track'
    end
  end

  devise_for :users

  get "main/index"
  get "main/api_autenticate"
  
  get "schedule_logs" => 'schedule_logs#index'
  delete "schedule_logs" => 'schedule_logs#destroy'
  

  root :to => 'main#index'

end

app/models/recommendation.rb
class Recommendation < ArtistUser
  attr_accessible :artist_id, :user_id, :show
  belongs_to :user
  belongs_to :artist

  scope :publick, where(show: true)
  
  scope :artists_date_range, lambda {|year_from, year_to|
    year_from = year_from.blank? ? 1000.years.ago : Time.new(year_from)
    year_to = year_to.blank? ? Time.now : Time.new(year_to)
    joins(:artist).where([  'artists.year_from > ? 
              AND (
                artists.year_to < ? OR 
                artists.year_to IS ?
              )', 
              year_from, 
              year_to, 
              nil])
  }
  scope :artists_more_than_listens, lambda {|count|
    joins(:artist).where([ 'artists.listeners > ?', count])
  }
  scope :artists_tagged_with, lambda {|tag_id|
    joins(:artist => :tags ).where(['tags.id = ?', tag_id])
  }

  class << self
    def filter(query, user)
      user_recom = select('DISTINCT "artist_users".*, "artists".*').includes(:artist).where(user_id: user.id).publick
      user_recom = user_recom.order('artist_users.created_at desc') unless query.try(:[], :s).present?
      tags = []
      query ||= {}
      search_attributes = {}
      if query.present? && query[:tagged_with].present?
        tags = query[:tagged_with].reject {|n| n.blank? }
        artist_ids = Artist.joins(:tags).select('artists.id, count(*) as taging').where(['tags.id in(?)', tags]).group('artists.id').having(['count(*) > ?', (tags.length - 1)]).map(&:id)
        artist_ids = [0] if artist_ids.blank?
        search_attributes.merge!(artist_id_in: artist_ids)
      end
      user_recom.search(query.merge(search_attributes))
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @selected_tags ||= []
    @selected_tags = Tag.find_all_by_id(params[:q][:tagged_with]) if params[:q].present?
    @top_tags = Tag.top_recommended(current_user)
    @search = Recommendation.filter(params[:q], current_user)
    @recommendations = @search.result.paginate(page: params[:page], per_page: (params[:per_page] || 25)) 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  def api_parse
    UserRecomendationsParser.new.delay.perform(@api_provider_aut.username, @api_provider_aut.session_key, current_user.id)
    flash[:notice] = t(:started_parsing) 
    redirect_to(:back)
  end

  def destroy
    @recommendation = current_user.recommendations.find(params[:id])
    respond_to do |format|
      if @recommendation.update_attribute(:show, false)
        format.html { redirect_to :back, notice: t(:entry_destroied) }
        format.json { render json: { message: t(:refused, name: @recommendation.artist.name)}  } # TODO finish ajax response
      else
        format.html { redirect_to :back, error: @recommendation.errors.full_messages }
        format.json { render json: { error: @recommendation.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_recommendation.html.haml
- cache(recommendation.artist) do
  - artist = recommendation.artist
  %tr
    %td= image_tag artist.photo.url
    %td= render partial: 'tags/tag', collection: artist.tags
    %td
      = link_to artist.name, artist.api_link, class: 'external', target: '_blank'
      %p
        = link_to "http://vk.com/search?c[performer]=1&c[q]=#{artist.name}&c[section]=audio", target: '_blank' do
          = image_tag "vk_logo.png", alt: "Прослушать на vk", width: '50px'
    %td= artist.year_from.nil? ? t(:none) : artist.year_from.strftime('%Y')
    %td= artist.year_to.nil? ? t(:none) : artist.year_to.strftime('%Y')
    %td= artist.listeners
    %td= l(artist.created_at)
    %td
      = link_to t('.destroy'), recommendation_path(recommendation), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, remote: true, :class => 'refuse btn btn-mini btn-danger', "data-type" => "json", 'data-loading-text' => t(:removing)

app/views/recommendations/_search.html.haml
%p.lead
  %h5
    = t(:search)
  = search_form_for @search, :class => "navbar-form navbar-left", role: "search" do |f|
    = f.text_field :artist_name_cont, placeholder: Artist.human_attribute_name(:name)
    = t('.listens_count')
    = f.number_field :artist_listeners_gt, step: 50_000
    = t('.year_from')
    = f.select :artist_year_from, options_for_select((Time.now.strftime('%Y').to_i.downto(1950)), selected: params[:year_from]), include_blank: true
    = t('.year_to')
    = f.select :artist_year_to, options_for_select((Time.now.strftime('%Y').to_i.downto(1950)), selected: params[:year_to]), include_blank: true
    %br
    = t(:per_page)
    = select_tag :per_page, options_for_select((25..200).step(25), selected: params[:per_page])
    = submit_tag t(:search)
    - if @top_tags.any?
      %ul{class: "nav nav-pills"} 
        - @selected_tags.each do |tag|
          = hidden_field_tag 'q[tagged_with][]', tag.id, class: 'tag_select'
        = hidden_field_tag 'q[tagged_with][]', '', class: 'tag_select'
        = render partial: 'tags/tag', collection: (@selected_tags + (@top_tags - @selected_tags))
        %i.icon-arrow-right.more_button{ display: 'none' }
  

app/views/recommendations/index.html.haml
- model_class = Artist
%h1= model_page_title(Recommendation)

%div#response
  = render partial: 'search'

= form_tag api_parse_recommendations_path(), method: :post do
  = link_to_or_authorize(@api_authorized, submit_tag(t('.parse_recommendations'), :confirm => t('.parsing_message')))

- if @recommendations.any?
  %table.table.table-striped#artist_table
    %thead
      %tr
        %th= model_class.human_attribute_name(:photo)
        %th= model_class.human_attribute_name(:tags)
        %th= sort_link @search, :artist_name
        %th= sort_link @search, :artist_year_from
        %th= sort_link @search, :artist_year_to
        %th= sort_link @search, :artist_listeners
        %th= sort_link @search, :created_at
        %th
    %tbody
      = render @recommendations
  = will_paginate @recommendations
- else
  = render 'main/empty_resource'
         

app/views/recommendations/toggle_visible.html.haml
%h1 Recommendations#toggle_visible
%p Find me in app/views/recommendations/toggle_visible.html.haml