config/routes.rb
MusicObserver::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "api_session/outside_request"
  get "api_session/return_callback"

  resources :recommendations, only: [:index, :destroy] do
    collection do
      post 'api_parse'
    end
  end

  resources :concerts, only: [:index] do
    member do
      put 'hide'
    end
  end

  resources :favorites, except: [:show] do
    collection do
      get 'api_search'
      post 'api_library'
      put 'pack_track'
    end

    member do
      put 'track'
    end
  end

  devise_for :users

  get "main/index"
  get "main/api_autenticate"
  
  get "schedule_logs" => 'schedule_logs#index'
  delete "schedule_logs" => 'schedule_logs#destroy'
  

  root :to => 'main#index'

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :api_link, :artist, :country, :description, :sity, :start_date, :street, :title, :api_id
  validates :api_link, :start_date, :title, :artist, :api_id, :presence => true
  has_many :concert_user_entries, dependent: :destroy
  belongs_to :artist

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png image/gif)
  
  extend ApplicationHelper

  scope :actual, lambda {  
  	interval = [Time.now, (Time.now + 1.year)]
  	order('start_date').where(['start_date BETWEEN ? AND ?', interval[0], interval[1]])
  }
  scope :is_show, where(['concert_user_entries.is_show = ?', true ])

  private 

  # def self.get_interval 
  # 	if interval_string.blank?
  		
  # 	end
  # 	[Time.parse(interval_string.split('-')[0]), Time.parse(interval_string.split('-')[1])]
  # end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  
  # GET /concerts
  # GET /concerts.json
  def index
    @search = Concert.order('start_date DESC').search(params[:q])
    @concerts = @search.result.paginate(page: params[:page], per_page: params[:per_page] || 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concerts }
    end
  end

  def hide
    concert = Concert.find(params[:id])
    concert_entry = ConcertUserEntry.get_user_concert_entry(concert, current_user)
    if concert_entry.update_attribute(:is_show, false)
      redirect_to :root, notice: t(:entry_hided)
    else
      redirect_to :root, notice: 'Errors.'
    end
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_concert.html.haml
- cache(concert) do
  %tr
    %td= image_tag concert.photo.url
    %td= link_to concert.title, concert.api_link, class: 'external '
    %td= truncate( strip_tags( concert.description ), length: 200, separator: " " )
    %td= concert.country
    %td= concert.sity
    %td= concert.street
    %td= link_to concert.artist.name, concert.artist.api_link, class: 'external '
    %td= concert.start_date

app/views/concerts/_form.html.haml
= form_for @concert, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :api_link, :class => 'control-label'
    .controls
      = f.text_field :api_link, :class => 'text_field'
  .control-group
    = f.label :country, :class => 'control-label'
    .controls
      = f.text_field :country, :class => 'text_field'
  .control-group
    = f.label :sity, :class => 'control-label'
    .controls
      = f.text_field :sity, :class => 'text_field'
  .control-group
    = f.label :street, :class => 'control-label'
    .controls
      = f.text_field :street, :class => 'text_field'
  .control-group
    = f.label :artist_id, :class => 'control-label'
    .controls
      = f.number_field :artist_id, :class => 'number_field'
  .control-group
    = f.label :start_date, :class => 'control-label'
    .controls
      = f.datetime_select :start_date, :class => 'datetime_select'
  .control-group
    = f.label :api_id, :class => 'control-label'
    .controls
      = f.number_field :api_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), concerts_path, :class => 'btn'

app/views/concerts/_search.html.haml
%p.lead
  %h5
    = t(".search")
  = search_form_for @search, :class => "navbar-form navbar-left", role: "search" do |f|
    = f.text_field :title_cont, placeholder: Favorite.human_attribute_name(:name)
    = f.text_field :start_date_gt, placeholder: t(:date_from), id: :date_from
    = f.text_field :start_date_lt, placeholder: t(:date_to), id: :date_to
    = t(:per_page)
    = select_tag :per_page, options_for_select((25..200).step(25), selected: params[:per_page])
    = f.submit t(:search)
    = f.submit t(:clear), :id => :q_reset

app/views/concerts/edit.html.haml
- model_class = Concert
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/concerts/index.html.haml
- model_class = Concert
.page-header
  %h1= model_page_title(model_class)

= render 'search'

- if @concerts.any?
  %table.table.table-striped
    %thead
      %tr
        %th
        %th= sort_link @search, :title
        %th= model_class.human_attribute_name(:description)
        %th= sort_link @search, :country
        %th= sort_link @search, :sity
        %th= model_class.human_attribute_name(:street)
        %th= sort_link @search, :artist_name
        %th= model_class.human_attribute_name(:start_date)
    %tbody
      = render partial: "concert", collection: @concerts
  = will_paginate @concerts
- else
  = render 'main/empty_resource'

app/views/concerts/new.html.haml
- model_class = Concert
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/concerts/show.html.haml
- model_class = Concert
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @concert.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @concert.description
%p
  %strong= model_class.human_attribute_name(:api_link) + ':'
  %br
  = @concert.api_link
%p
  %strong= model_class.human_attribute_name(:country) + ':'
  %br
  = @concert.country
%p
  %strong= model_class.human_attribute_name(:sity) + ':'
  %br
  = @concert.sity
%p
  %strong= model_class.human_attribute_name(:street) + ':'
  %br
  = @concert.street
%p
  %strong= model_class.human_attribute_name(:artist_id) + ':'
  %br
  = @concert.artist_id
%p
  %strong= model_class.human_attribute_name(:start_date) + ':'
  %br
  = @concert.start_date
%p
  %strong= model_class.human_attribute_name(:api_id) + ':'
  %br
  = @concert.api_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), concerts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_concert_path(@concert), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), concert_path(@concert), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'