config/routes.rb
MusicObserver::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "api_session/outside_request"
  get "api_session/return_callback"

  resources :recommendations, only: [:index, :destroy] do
    collection do
      post 'api_parse'
    end
  end

  resources :concerts, only: [:index] do
    member do
      put 'hide'
    end
  end

  resources :favorites, except: [:show] do
    collection do
      get 'api_search'
      post 'api_library'
      put 'pack_track'
    end

    member do
      put 'track'
    end
  end

  devise_for :users

  get "main/index"
  get "main/api_autenticate"
  
  get "schedule_logs" => 'schedule_logs#index'
  delete "schedule_logs" => 'schedule_logs#destroy'
  

  root :to => 'main#index'

end

app/models/schedule_log.rb
class ScheduleLog
  include Mongoid::Document
  include Mongoid::Timestamps
  extend Enumerize

  default_scope order_by(_id: -1)

  field :job_class, type: String
  field :status, type: String
  enumerize :status, in: [:debug, :info, :warn, :error], default: :info
  field :content, type: String
  field :entry_type
  enumerize :entry_type, in: [:job_started, :job_ended, :entry], default: :entry

  def self.get_logs tasks, status, start_date, end_date, page, limit 
    query = { "job_class" => { "$in" => tasks } }
    query.merge!({ status: status }) unless status.blank?
    date_range = { created_at: {}}
    date_range[:created_at].merge!({:$gte => Time.parse(start_date)}) unless start_date.blank?
    date_range[:created_at].merge!({:$lte => Time.parse(end_date)}) unless end_date.blank?
    query.merge!(date_range) unless date_range[:created_at].blank?
    self.where(query).paginate(page: page, per_page: limit)
  end
end

app/controllers/schedule_logs_controller.rb
class ScheduleLogsController < ApplicationController
  
  def index
    @job_classes = ScheduleLog.distinct(:job_class)
    @delay_jobs_stat = delay_jobs_stat
    if params[:job_classes].blank?
      @items = ScheduleLog.paginate(page: params[:page], per_page: params[:per_page])
    else
      @items = ScheduleLog.get_logs(params[:job_classes], params[:status], params[:date_from], params[:date_to], params[:page], params[:per_page] || 30)
    end
   end

  def destroy
    Delayed::Job.destroy_all
    respond_to do |format|
      format.html { flash[:success] = t(:success); redirect_to :back }
      format.json { render json: { title: t(:success), message: t(:cleared) } }
    end
   end
private
  def del_job_last_error
    worker = Delayed::Job.where(:last_error.ne => nil, :last_error.exists => true).last
    return if worker.blank?
    worker.last_error.split("\n").join("<br>") if worker.last_error
  end
    def delay_jobs_stat
      {
        'Jobjs in queue: ' => Delayed::Job.all.count,  
        'Failed jobs in queue' => Delayed::Job.where(:last_error.ne => nil, :last_error.exists => true).count,
        'Job last_error' => del_job_last_error
      }
    end
end

app/views/schedule_logs/_filter.html.haml
= form_tag schedule_logs_path, id: 'logs_form', method: :get do
  = hidden_field_tag :job_class, params[:job_class] 
  = label_tag :status, t('.status')
  = select_tag :status, options_for_select([ScheduleLog.status.values, ''].flatten, selected: params[:status] || '')
  = label_tag :status, t('.date_range')
  = text_field_tag 'date_from', params[:date_from], placeholder: t(:date_from)
  = text_field_tag 'date_to', params[:date_to], placeholder: t(:date_to)
  = label_tag :per_page, t(:per_page)
  = select_tag :per_page, options_for_select((50..200).step(50), selected: params[:per_page])
  - if @job_classes.any?
    %ul{class: "nav nav-pills"} 
      = hidden_field_tag 'job_classes[]', '', class: 'tag_select'
      - if params[:job_classes]
        - params[:job_classes].select {|n| !n.blank? }.each do |job|
          = hidden_field_tag 'job_classes[]', job, class: 'tag_select'
      - @job_classes.each do |job|
        - html = (params[:job_classes] && params[:job_classes].include?(job.to_s)) ? 'active' : '' 
        %li{class: "#{html}" }
          = link_to job, schedule_logs_path(:job_class => job), id: "job_#{job}"
  = submit_tag t(:filter)

app/views/schedule_logs/_worker_status.html.haml
%p
  %ul
    %li
      %i.icon-wrench
        Resque worker:
    - if get_worker_pid 
      %span.label.label-success
        ON
    -else
      %span.label.label-important
        OFF
    %li
      %i.icon-time
        Resque scheduler:
    - if get_scheduler_pid 
      %span.label.label-success
        ON
    - else
      %span.label.label-important
        OFF
%p
  %p        
    %i.icon-ok
      Processed:
    %span.badge
      = worker.processed
  %p
    %i.icon-remove
      Failed:
    %span.badge.badge-important
      = worker.failed
  %p
    %i.icon-road
      Working:
    %span.label.label-info
      = "#{worker_processing} (#{worker_run_at})"

- unless last_failed.blank?
  %p
    Last failed task: 
    %b= last_failed

app/views/schedule_logs/index.html.haml
- @delay_jobs_stat.each do |name, val|
  - if val.try {|n| n.to_s.length > 0 }
    %b= name
    - if val.try {|n| n.to_s.length > 200 }
      %p{ class: 'long truncated' }
    - else
      %span
        = raw val
= link_to schedule_logs_path, method: :delete, class: 'simple_remote', 'data-type' => 'json', 'data-loading-text' => t(:in_work), remote: true do
  %i.icon-remove
  Clear job queue
%hr

= render partial: 'filter'
    
- if @items.length > 0
  - @items.each do |item|
    - html = item.status == 'error' ? 'alert alert-error' : ''
    - html += ' long truncated' if item.try {|n| n.content.length > 200 }
    %div{ class: "#{html}" }
      = h(raw "[ #{item.status.upcase}: #{item.created_at.strftime('%H:%M:%S %d-%m-%Y')} ] #{item.content}")
  = will_paginate @items
- else 
  %h3
    = t(:empty_entries)